spring.application.name=megacity

spring.datasource.url=jdbc:mysql://localhost:3306/mcc-v2?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database=mysql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.generate-ddl=true
spring.jpa.show-sql=false

# JWT Config
jwt.secret=Tbk0S2RyZGlUYRfWaNca558FEfXE0VA+G36Mgnrznhk
jwt.access-expiration=1m
jwt.refresh-expiration=20m

server.port=8081